export default [
	{
		login: "LTTien",
		id: 12224777,
		node_id: "MDQ6VXNlcjEyMjI0Nzc3",
		avatar_url: "https://avatars.githubusercontent.com/u/12224777?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/LTTien",
		html_url: "https://github.com/LTTien",
		followers_url: "https://api.github.com/users/LTTien/followers",
		following_url: "https://api.github.com/users/LTTien/following{/other_user}",
		gists_url: "https://api.github.com/users/LTTien/gists{/gist_id}",
		starred_url: "https://api.github.com/users/LTTien/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/LTTien/subscriptions",
		organizations_url: "https://api.github.com/users/LTTien/orgs",
		repos_url: "https://api.github.com/users/LTTien/repos",
		events_url: "https://api.github.com/users/LTTien/events{/privacy}",
		received_events_url: "https://api.github.com/users/LTTien/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "maguil53",
		id: 19479641,
		node_id: "MDQ6VXNlcjE5NDc5NjQx",
		avatar_url: "https://avatars.githubusercontent.com/u/19479641?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/maguil53",
		html_url: "https://github.com/maguil53",
		followers_url: "https://api.github.com/users/maguil53/followers",
		following_url:
			"https://api.github.com/users/maguil53/following{/other_user}",
		gists_url: "https://api.github.com/users/maguil53/gists{/gist_id}",
		starred_url: "https://api.github.com/users/maguil53/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/maguil53/subscriptions",
		organizations_url: "https://api.github.com/users/maguil53/orgs",
		repos_url: "https://api.github.com/users/maguil53/repos",
		events_url: "https://api.github.com/users/maguil53/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/maguil53/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "emmanuelcodev",
		id: 31635722,
		node_id: "MDQ6VXNlcjMxNjM1NzIy",
		avatar_url: "https://avatars.githubusercontent.com/u/31635722?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/emmanuelcodev",
		html_url: "https://github.com/emmanuelcodev",
		followers_url: "https://api.github.com/users/emmanuelcodev/followers",
		following_url:
			"https://api.github.com/users/emmanuelcodev/following{/other_user}",
		gists_url: "https://api.github.com/users/emmanuelcodev/gists{/gist_id}",
		starred_url:
			"https://api.github.com/users/emmanuelcodev/starred{/owner}{/repo}",
		subscriptions_url:
			"https://api.github.com/users/emmanuelcodev/subscriptions",
		organizations_url: "https://api.github.com/users/emmanuelcodev/orgs",
		repos_url: "https://api.github.com/users/emmanuelcodev/repos",
		events_url: "https://api.github.com/users/emmanuelcodev/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/emmanuelcodev/received_events",
		type: "User",
		site_admin: false,
	},

  
];
