export default {
	login: "aicprog",
	id: 31829556,
	node_id: "MDQ6VXNlcjMxODI5NTU2",
	avatar_url: "https://avatars.githubusercontent.com/u/31829556?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/aicprog",
	html_url: "https://github.com/aicprog",
	followers_url: "https://api.github.com/users/aicprog/followers",
	following_url: "https://api.github.com/users/aicprog/following{/other_user}",
	gists_url: "https://api.github.com/users/aicprog/gists{/gist_id}",
	starred_url: "https://api.github.com/users/aicprog/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/aicprog/subscriptions",
	organizations_url: "https://api.github.com/users/aicprog/orgs",
	repos_url: "https://api.github.com/users/aicprog/repos",
	events_url: "https://api.github.com/users/aicprog/events{/privacy}",
	received_events_url: "https://api.github.com/users/aicprog/received_events",
	type: "User",
	site_admin: false,
	name: "Adriany Cocom",
	company: null,
	blog: "",
	location: null,
	email: null,
	hireable: null,
	bio: null,
	twitter_username: null,
	public_repos: 11,
	public_gists: 0,
	followers: 3,
	following: 3,
	created_at: "2017-09-10T19:53:55Z",
	updated_at: "2021-09-20T15:38:38Z",
};
